# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ynn1999/FJTPDS/Lab3333.cache/wt [current_project]
set_property parent.project_path C:/Users/ynn1999/FJTPDS/Lab3333.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ynn1999/FJTPDS/Lab3333.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/imports/Lab3/lab3_1/lab3_1.srcs/sources_1/new/vga.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/imports/Lab3/new-20201102T023832Z-001/new/Combine.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/keyboard-driver.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/CLK1HZ.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/GenerSequen.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/Start.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/Gst.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/displaydiff.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/top.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/alarm_power.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/clock_divider.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/clock1.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/v_counter.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/alarm.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/led.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/bin_dec1.v
  C:/Users/ynn1999/FJTPDS/Lab3333.srcs/sources_1/new/h_counter.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ynn1999/FJTPDS/Lab3333.srcs/constrs_1/imports/Desktop/Nexys4DDR_Master22.xdc
set_property used_in_implementation false [get_files C:/Users/ynn1999/FJTPDS/Lab3333.srcs/constrs_1/imports/Desktop/Nexys4DDR_Master22.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Combine -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Combine.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Combine_utilization_synth.rpt -pb Combine_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
